# Generated by Django 4.0.3 on 2022-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('picture1', models.CharField(blank=True, help_text='以下はギャラリー部分', max_length=100, null=True)),
                ('picture2', models.CharField(blank=True, max_length=100, null=True)),
                ('picture3', models.CharField(blank=True, max_length=100, null=True)),
                ('picture4', models.CharField(blank=True, max_length=100, null=True)),
                ('picture5', models.CharField(blank=True, max_length=100, null=True)),
                ('picture6', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
