# Generated by Django 4.0.3 on 2022-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='pictureMain',
            field=models.CharField(blank=True, help_text='一番上に単体で表示', max_length=100, null=True),
        ),
    ]
