#インストールされているバージョンによって末尾の数字調整
runtime: python39

# 下記は 設定用ディレクトリ.wsgi:application のように記述
entrypoint: gunicorn -b :$PORT portfolio.wsgi:application



# 下記はhttpでアクセスがあった際、httpsにリダイレクトするための記述
handlers:
- url:  /static
  static_dir: staticfiles/

- url: .*
  secure: always
  script: auto
