# Generated by Django 3.2.6 on 2021-09-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
