# Generated by Django 3.2.6 on 2021-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
