# Generated by Django 3.2.6 on 2021-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_alter_picturemodel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturemodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='picture1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='picture2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='picture3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='picture4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
    ]
