# Generated by Django 3.2.6 on 2021-09-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20210915_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturemodel',
            name='picture5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='picture6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='picture'),
        ),
    ]
