# Generated by Django 3.2.6 on 2021-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_auto_20211015_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='picture2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture6',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
