# Generated by Django 3.2.6 on 2021-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20211015_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
