# Generated by Django 3.2.6 on 2021-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_alter_picturemodel_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
