# Generated by Django 4.0.3 on 2022-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('3dcg', '3dcg'), ('web', 'web'), ('other', 'other')], max_length=30, null=True)),
            ],
        ),
    ]
