# Generated by Django 4.1 on 2022-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notesmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='tag',
            field=models.CharField(blank=True, choices=[('3dcg', '3dcg'), ('AfterEffects', 'AfterEffects'), ('web', 'web'), ('Linux', 'Linux'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
