# Generated by Django 3.2.6 on 2021-11-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PictureModel',
            new_name='ModelingModel',
        ),
    ]
