# Generated by Django 3.2.6 on 2021-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('movie', models.TextField(blank=True, null=True)),
                ('picture1', models.CharField(max_length=200)),
                ('picture2', models.CharField(blank=True, max_length=200, null=True)),
                ('picture3', models.CharField(blank=True, max_length=200, null=True)),
                ('picture4', models.CharField(blank=True, max_length=200, null=True)),
                ('picture5', models.CharField(blank=True, max_length=200, null=True)),
                ('picture6', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
