# Generated by Django 3.2.6 on 2021-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notemodel_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='abstract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
