# Generated by Django 4.1 on 2022-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.TextField()),
                ('youtube', models.TextField(blank=True, null=True)),
                ('vimeo', models.TextField(blank=True, null=True)),
                ('niconico', models.TextField(blank=True, null=True)),
                ('picture1', models.TextField(blank=True, null=True)),
                ('picture2', models.TextField(blank=True, null=True)),
                ('picture3', models.TextField(blank=True, null=True)),
                ('picture4', models.TextField(blank=True, null=True)),
                ('picture5', models.TextField(blank=True, null=True)),
                ('picture6', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('pictre', 'Picture'), ('movie', 'Movie'), ('modeling', 'Modeling'), ('other', 'other')], max_length=30)),
            ],
        ),
    ]
