# Generated by Django 4.1 on 2022-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksmodel',
            name='niconico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='thumbnail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='vimeo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
