# Generated by Django 4.1 on 2022-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_worksmodel_niconico_alter_worksmodel_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksmodel',
            name='pictureMain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
