# Generated by Django 4.1 on 2022-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_worksmodel_picturemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='niconico',
            field=models.CharField(blank=True, help_text='niconicoのID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='picture1',
            field=models.CharField(blank=True, help_text='以下はギャラリー部分', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='pictureMain',
            field=models.CharField(blank=True, help_text='一番上に単体で表示', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='vimeo',
            field=models.CharField(blank=True, help_text='vimeoのID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='youtube',
            field=models.CharField(blank=True, help_text='youtubeのID', max_length=100, null=True),
        ),
    ]
