# Generated by Django 4.1 on 2022-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_worksmodel_date_alter_worksmodel_niconico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksmodel',
            name='tag',
            field=models.CharField(choices=[('picture', 'Picture'), ('movie', 'Movie'), ('modeling', 'Modeling'), ('other', 'other')], max_length=30),
        ),
    ]
